# Generated by Django 6.0.1 on 2026-02-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='attempt_type',
            field=models.CharField(choices=[('baseline', 'Baseline'), ('reassessment', 'Reassessment'), ('practice', 'Practice')], default='baseline', max_length=20),
        ),
    ]
