# Generated by Django 6.0.1 on 2026-02-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_engine', '0002_assessmentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='roadmap',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='weaknesses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
